_target_: uni2ts.model.moirai.MoiraiForecast
module_kwargs:
  _target_: builtins.dict
  distr_output:
    _target_: uni2ts.distribution.MixtureOutput
    components:
      - _target_: uni2ts.distribution.StudentTOutput
      - _target_: uni2ts.distribution.NormalFixedScaleOutput
      - _target_: uni2ts.distribution.NegativeBinomialOutput
      - _target_: uni2ts.distribution.LogNormalOutput
  d_model: 1536
  num_layers: 32
  patch_sizes: ${as_tuple:[8, 16, 32, 64, 128]}
  max_seq_len: 512
  attn_dropout_p: 0.0
  dropout_p: 0.0
  scaling: true
num_samples: 100
patch_size: ???
context_length: ???
checkpoint: /home/qingrenyao/data/checkpoints/moirai_1B/epoch2999.ckpt